# Generated by Django 2.2.3 on 2019-07-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chotatsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('first_category', models.CharField(max_length=128)),
                ('second_category', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
